USE ASTRONOMY_DB
GO

DROP TABLE IsVisible
DROP TABLE Stars
DROP TABLE Explore
DROP TABLE Satellites
DROP TABLE Observe
DROP TABLE Researchers
DROP TABLE Planets
DROP TABLE Astronauts
DROP TABLE SolarSystems
DROP TABLE Galaxies

GO

CREATE TABLE Galaxies(
	GID INT PRIMARY KEY,
	GName VARCHAR(30)
)
CREATE TABLE SolarSystems(
	SSID INT PRIMARY KEY,
	SSName VARCHAR(30),
	GID INT REFERENCES Galaxies(GID)
)

CREATE TABLE Planets
	(PlanetID INT PRIMARY KEY,
	PName VARCHAR(30),
	PMass FLOAT,
	PPopulation INT,
	SSID INT REFERENCES SolarSystems(SSID)
	)
CREATE TABLE Researchers(
	ResearcherID INT PRIMARY KEY,
	RName VARCHAR(30),
	RDoB DATE,
	RDepartment VARCHAR(30)
	)
CREATE TABLE Observe(
	PID INT REFERENCES Planets(PlanetID),
	RID INT REFERENCES Researchers(ResearcherID),
	DoOBS DATETIME,
	Obs VARCHAR(80),
	CONSTRAINT PK_Observe PRIMARY KEY(PID,RID,DoOBS)
)
CREATE TABLE Astronauts(
	AstronautID INT PRIMARY KEY,
	AName VARCHAR(30),
	ADoB DATE
)
CREATE TABLE Satellites(
	SatID INT PRIMARY KEY,
	SatName VARCHAR(30),
	PID INT REFERENCES Planets(PlanetID)
)
CREATE TABLE Explore(
	AstronautID INT REFERENCES Astronauts(AstronautID),
	SatID INT REFERENCES Satellites(SatID),
	DoEXP DATE,
	EXPConclusion VARCHAR(80),
	EXPDuration INT,
	CONSTRAINT PK_Explore PRIMARY KEY(AstronautID,SatID,DoEXP)
)
CREATE TABLE Stars(
	StarID INT PRIMARY KEY,
	StarName VARCHAR(30),
	Constellation VARCHAR(30),
	SSID INT REFERENCES SolarSystems(SSID)
)
CREATE TABLE IsVisible(
	StarID INT REFERENCES Stars(StarID),
	PlanetID INT REFERENCES Planets(PlanetID),
	Distance INT,
	CONSTRAINT PK_IsVisible PRIMARY KEY(StarID, PlanetID)
)

