USE MINIASTRONOMY
GO

CREATE OR ALTER PROC PhantomRead2
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
	BEGIN TRAN
	SELECT * FROM MiniPlanets
	WAITFOR DELAY '00:00:05'
	SELECT * FROM MiniPlanets
	COMMIT TRAN
END

GO
EXEC PhantomRead2

GO
CREATE OR ALTER PROC PhantomReadSolution
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
	BEGIN TRAN
	SELECT * FROM MiniPlanets
	WAITFOR DELAY '00:00:05'
	SELECT * FROM MiniPlanets
	COMMIT TRAN
END

GO
EXEC PhantomReadSolution