USE MINIASTRONOMY
GO
-- this does not work for some reason
ALTER DATABASE MINIASTRONOMY SET ALLOW_SNAPSHOT_ISOLATION ON
ALTER DATABASE MINIASTRONOMY SET ALLOW_SNAPSHOT_ISOLATION OFF
-- OR
-- ALTER DATABASE MINIASTRONOMY SET READ_COMMITTED_SNAPSHOT ON
-- ALTER DATABASE MINIASTRONOMY SET READ_COMMITTED_SNAPSHOT OFF
GO
DELETE FROM LogTable
DELETE FROM MiniOBS
DELETE FROM MiniPlanets
DELETE FROM MiniResearchers

DBCC CHECKIDENT ('MiniPlanets', RESEED, 0);
DBCC CHECKIDENT ('MiniResearchers', RESEED, 0);

GO
INSERT INTO MiniPlanets(PName, PDensity, PPopulation) VALUES 
('Mercury', 5.4, 0),
('Venus', 5.2, 0)

GO

CREATE OR ALTER PROC Snapshot1
AS
BEGIN
	WAITFOR DELAY '00:00:10'
	BEGIN TRAN
	UPDATE MiniPlanets SET PName = 'Snapshot1 Planet' WHERE PID=1
	WAITFOR DELAY '00:00:10'
	COMMIT TRAN
END

GO
EXEC Snapshot1