USE MINIASTRONOMY
GO

CREATE OR ALTER PROC NonRepeatableRead2
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ COMMITTED
	BEGIN TRAN
	SELECT * FROM MiniPlanets
	WAITFOR DELAY '00:00:05'
	SELECT * FROM MiniPlanets
	COMMIT TRAN
END

EXEC NonRepeatableRead2

GO
CREATE OR ALTER PROC NonRepeatableReadSolution
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
	BEGIN TRAN
	SELECT * FROM MiniPlanets
	WAITFOR DELAY '00:00:05'
	SELECT * FROM MiniPlanets
	COMMIT TRAN
END

EXEC NonRepeatableReadSolution