USE MINIASTRONOMY
GO

CREATE OR ALTER PROC DirtyRead2
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	BEGIN TRANSACTION
	SELECT * FROM MiniPlanets
	WAITFOR DELAY '00:00:15'
	SELECT * FROM MiniPlanets
	COMMIT TRAN
END

EXEC DirtyRead2
GO

CREATE OR ALTER PROC DirtyReadSolution
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ COMMITTED
	BEGIN TRANSACTION
	SELECT * FROM MiniPlanets
	WAITFOR DELAY '00:00:15'
	SELECT * FROM MiniPlanets
	COMMIT TRAN
END

EXEC DirtyReadSolution